# normal serever up
server {
  listen 80;
  server_name locathost;   #herolab.internal; --> also need to add in /etc/hosts

  location / {
      root /usr/share/nginx/html;  #/usr/share/nginx/html/hero; # location os project index
      index  hero.html;
  }
  }


# location for nginx configuration----> /etc/nginx    (nginx.conf)
# that file route to (conf.d directory or sites-available directory)
# cd /etc/nginx/conf.d/file.conf
# content folder /usr/share/nginx/html
