upstream backend {
            #least_connection;
            server 3.110.167.125 max_fails=3 fail_timeout=30s;
            server 3.123.123.123;
}
server{
  listen 80;
  server_name _;

  location / {
      proxy_pass http://backend;
  }
}


# By Default - Round robin
# Ip_hash; - any server
# least_connection;  less connected will asign
  
